### ISSUE TITLE
ToSlice dose not re-empty the dist slice

### ISSUE THREAD

**Issue by aisk** [ahmetalpbalkan/go-linq#43] opened 2016-11-30 07:30 UTC
Codes:

```go
func main() {
	l := []string{"foo", "bar", "baz"}
	linq.From(l).ToSlice(&l)
	fmt.Println(l)
}
```

Result:

```
[foo bar baz foo bar baz]
```

go-linq version:

```
- name: github.com/ahmetalpbalkan/go-linq
  version: 8985ec99e11a8bff7eb19dd0a0b2187770dab23a
```

I don't know whether this is a bug or a feature, but if this is a feature, I think it's better to have this behavior documented on `ToSlice`'s API doc.

**Comment by ahmetalpbalkan** [comment] 2016-12-01 22:25
cc: @kalaninja any ideas?

**Comment by kalaninja** [comment] 2016-12-02 15:14
Yes, it is not a bug. The idea is that the go-linq user prepares the storage and decides whether to clean it or not. I thought that it is quite obvious from the doc, since here is nothing about cleaning the result slice:

> ToSlice iterates over a collection and populates result slice

But If it is not, I may document this behaviour. what do you think @ahmetalpbalkan ?

**Comment by ahmetalpbalkan** [comment] 2016-12-02 18:46
In this case, I think the documentation is good enough but since apparently people can easily do this mistake, we can just say it does not clear the existing slice.

**Comment by ahmetalpbalkan** [comment] 2016-12-02 18:48
This is like pre-populating a struct's fields and then saying `json.Unmarshal(b, &v)` is not clearing the fields which were set previously and missing from the unmarshaled json object. I think our design is just fine.

**Comment by cleitonmarx** [comment] 2016-12-05 05:57
What about to add a method AppendToSlice (with same behavior of actual ToSlice function) and change the behavior of ToSlice to over result pointer to a new slice pointer as proposed here #46?

**Comment by ahmetalpbalkan** [comment] 2016-12-05 06:29
@cleitonmarx I can't think of a case of why someone would pass us a slice to be replaced with a new slice instance. What would be a good use case for that?

**Comment by aisk** [comment] 2016-12-05 08:01
@ahmetalpbalkan Hi I have a question, if I have a list of whatever, I want to order them "in place" like this:

```go
l := []string{"foo", "bar", "baz"}
l = linq.From(l).Results()
```

then go will complains:

```
cannot use linq.From(l).Results() (type []interface {}) as type []string in assignment
```

So I added the `.([]string)` like this:

```go
l := []string{"foo", "bar", "baz"}
l = linq.From(l).Results().([]string)
```

but go still complains:

```
invalid type assertion: linq.From(l).Results().([]string) (non-interface type []interface {} on left)
```

So I need the `ToSlice` function to do this, or is there some way to do this better which I am missing?

**Comment by cleitonmarx** [comment] 2016-12-05 08:23
As a ".NET LINQ-like" library, I think that the behavior of ToSlice should be the same as the original LINQ ToList. In ToList implementation the return is always a [new instance](https://github.com/dotnet/corefx/blob/e6b6ba11c0b7541fb7dc8eac769bf541f5ece3c3/src/System.Linq/src/System/Linq/ToCollection.cs#L30).
A good use case is ordering a slice using linq (example found [here](https://github.com/dotnet/corefx/blob/77f844f3f05bb85d9f6d6b9ae1c1a7d3cef327aa/src/System.Data.SqlClient/tests/Tools/TDS/TDS/PreLogin/TDSPreLoginToken.cs#L161)):

using C#:
```csharp
options = options.OrderBy(o => o.Position).ToList();
```

using Go:
```go
From(options).OrderBy(func(o interface{}) interface{}{
  return o.(Option).Position
}).ToSlice(&options);
```

Actually, the code in Go will not have the same result of the C# code.

**Comment by kalaninja** [comment] 2016-12-05 08:41
@aisk Yes, you have to use `ToSlice` function.
```go
result := make([]string{}, 3)
l := []string{"foo", "bar", "baz"}
linq.From(l).OrderBy(func(a interface{}) interface{}{
  return true;
}).ToSlice(&result)
```

**Comment by aisk** [comment] 2016-12-05 09:25
@kalaninja Yes I am writing codes like what you pasted, and then this pull request is created ...

Now I am created a new slice to receive the result. But as you know, naming a variable is hard in software engineering... So I think is more convenient if we had a new method (or change the `ToSlice`'s behavior).

**Comment by kalaninja** [comment] 2016-12-05 09:58
@aisk I understand your concerns, [here](https://github.com/ahmetalpbalkan/go-linq/pull/46#issuecomment-264805633) is what I offer.

**Comment by ahmetalpbalkan** [comment] 2016-12-15 19:59
BTW the work to redefine `ToSlice()` is actively ongoing at #46. @aisk we now empty the passed slice and shrink/grow it based on the result size. It'll be available in v3.0 release.

**Comment by aisk** [comment] 2016-12-16 05:49
@ahmetalpbalkan great!

**Comment by ahmetalpbalkan** [comment] 2017-01-01 23:41
Fixed in v3-dev branch.

**Closed by ahmetalpbalkan** 2017-01-01 23:41 UTC
Labels: question
